import mongoose from 'mongoose';
import dotenv from 'dotenv';
import bcrypt from 'bcryptjs';
import fs from 'fs';
import path from 'path';
import { createRequire } from 'module';
const require = createRequire(import.meta.url);
const PDFDocument = require('pdfkit');

dotenv.config();
import Book from './models/bookModel.js';
import User from './models/userModel.js';

const CATEGORIES = [
  'Engineering', 'Agriculture', 'Coding', 'Motivational', 
  'Science', 'History', 'Fiction', 'Business', 'Health', 
  'Art', 'Technology', 'Mathematics', 'Psychology', 'Self-Help', 'Sci-Fi', 'Adventure', 'Romance'
];

const TITLES_PART1 = ['The ', 'How to ', 'Secrets of ', 'Understanding ', 'Advanced ', 'Principles of ', 'The Complete Guide to ', 'Mastering '];
const TITLES_PART2 = ['Mind', 'Future', 'Universe', 'Code', 'Life', 'Success', 'Money', 'Space', 'History', 'Psychology', 'Art', 'Love', 'Physics', 'Biology', 'Chemistry'];
const AUTHORS = ['Dr. A. Smith', 'J. K. Doe', 'Robert Williams', 'Sarah Connor', 'Alan Turing', 'Marie Curie', 'Isaac Newton', 'Jane Austen', 'Carl Sagan', 'Stephen Hawking'];

// Color Palette for Different Covers
const BOOK_COLORS = [
  '4f46e5', // Indigo
  'dc2626', // Red
  '16a34a', // Green
  'd97706', // Amber
  '2563eb', // Blue
  '9333ea', // Purple
  'db2777', // Pink
  '059669', // Teal
  '7c3aed', // Violet
  '0891b2', // Cyan
  'ea580c', // Orange
  'be123c', // Rose
  '0d9488', // Cyan Dark
  'b91c1c', // Red Dark
  '4338ca'  // Indigo Dark
];

const connectDB = async () => {
  try {
    const conn = await mongoose.connect(process.env.MONGO_URI || 'mongodb://localhost:27017/librosys');
    console.log(`MongoDB Connected`);
  } catch (error) {
    console.error(`Error: ${error.message}`);
    process.exit(1);
  }
};

const createPDF = (bookData, index) => {
  return new Promise((resolve, reject) => {
    const filename = `book_${Date.now()}_${index}.pdf`;
    const filePath = path.join('uploads', filename);
    const doc = new PDFDocument();

    doc.pipe(fs.createWriteStream(filePath));

    // PDF Cover Design
    doc.rect(0, 0, 612, 792).fill('#f3f4f6'); 
    doc.rect(50, 50, 512, 692).fill('white');
    doc.strokeColor('#4f46e5');
    doc.lineWidth(5);
    doc.rect(50, 50, 512, 692).stroke();

    doc.fillColor('#4f46e5');
    doc.fontSize(30).text('LIBROSYS', 306, 100, { align: 'center', underline: true });
    
    doc.fillColor('black');
    doc.fontSize(24).text(bookData.title, 306, 200, { align: 'center', width: 400 });
    doc.fillColor('gray');
    doc.fontSize(16).text(`By ${bookData.author}`, 306, 250, { align: 'center' });
    doc.fillColor('#4f46e5');
    doc.fontSize(12).text(bookData.category.toUpperCase(), 306, 300, { align: 'center' });

    // Sample Content
    doc.fillColor('black');
    doc.fontSize(10);
    const loremText = "This is a generated sample book for the LibroSys library management system. It allows users to test the download and preview features. The Neural Vibe Matcher analyzes your emotions to find the perfect book. This text repeats to simulate pages. ";
    let y = 400;
    for (let i = 0; i < 30; i++) { 
        doc.text(loremText, 70, y, { width: 472 });
        y += 50;
        if(y > 700) break; 
    }
    doc.fontSize(8).fillColor('gray');
    doc.text(`Generated by LibroSys • ID: ${bookData.id}`, 306, 770, { align: 'center' });
    doc.end();

    doc.on('end', () => resolve(filename));
  });
};

const generateBooks = async (count) => {
  const books = [];
  if (!fs.existsSync('uploads')) fs.mkdirSync('uploads');

  console.log(`Generating ${count} Books with PDFs and Covers...`);
  
  for (let i = 0; i < count; i++) {
    const cat = CATEGORIES[Math.floor(Math.random() * CATEGORIES.length)];
    const part1 = TITLES_PART1[Math.floor(Math.random() * TITLES_PART1.length)];
    const part2 = TITLES_PART2[Math.floor(Math.random() * TITLES_PART2.length)];
    const title = `${part1}${part2}`;
    const author = AUTHORS[Math.floor(Math.random() * AUTHORS.length)];
    const uniqueId = `BK${10000 + i}`;
    
    // 1. Create the PDF File
    const fileName = await createPDF({ title, author, category: cat, id: uniqueId }, i);
    
    // 2. Create a Unique Cover Image URL
    // Random color + Title + Author
    const randomColor = BOOK_COLORS[Math.floor(Math.random() * BOOK_COLORS.length)];
    const coverUrl = `https://placehold.co/300x450/${randomColor}/white?text=${encodeURIComponent(title)}\nby ${encodeURIComponent(author)}&font=roboto&fontweight=bold`;
    
    books.push({
      title: `${title} ${uniqueId}`,
      author: author,
      category: cat,
      description: `A comprehensive guide to ${cat}. This book explores the depths of ${part2.toLowerCase()}. Includes advanced techniques and practical examples.`,
      status: 'Available',
      pages: Math.floor(Math.random() * 300) + 100,
      fileUrl: fileName,
      coverUrl: coverUrl // Store the unique image
    });
  }
  return books;
};

const seedDB = async () => {
  try {
    await connectDB();
    console.log('Starting Database Seed...');

    // Clean up old data
    await Book.deleteMany();
    const uploadsDir = 'uploads';
    if (fs.existsSync(uploadsDir)){
        fs.readdirSync(uploadsDir).forEach(file => {
            if(file.endsWith('.pdf')) fs.unlinkSync(path.join(uploadsDir, file));
        });
    }
    console.log('Old files cleaned.');

    // Generate 50 Books
    const booksToInsert = await generateBooks(50);
    await Book.insertMany(booksToInsert);
    console.log('50 Books with Different Covers inserted!');

    // Setup Admin
    let admin = await User.findOne({ email: 'admin@librosys.com' });
    const hashedPassword = await bcrypt.hash('123456', 10);
    if (admin) {
        admin.password = hashedPassword;
        await admin.save();
        console.log('Admin password updated.');
    } else {
        await User.create({ name: 'Admin User', email: 'admin@librosys.com', password: hashedPassword, role: 'admin' });
        console.log('Admin User Created');
    }

    console.log('Seeding Complete!');
    process.exit();
  } catch (error) {
    console.error(`Error: ${error.message}`);
    process.exit(1);
  }
};

seedDB();